import Link from "next/link";
import { listNotificationsForUser } from "@reachfyp/api";
import { GlassPanel } from "@reachfyp/ui";
import { redirect } from "next/navigation";
import { getCurrentSessionUser } from "../../../lib/auth/session";
import { MarketplaceTopNav } from "../../marketplace-top-nav";

type NotificationsPageProps = {
  searchParams?: Promise<{
    status?: string;
  }>;
};

const notificationStatusMessages: Record<string, string> = {
  read: "The selected notification was marked as read.",
  "read-all": "All notifications are marked as read.",
};

export default async function NotificationsPage({ searchParams }: NotificationsPageProps) {
  const currentUser = await getCurrentSessionUser();

  if (!currentUser) {
    redirect("/auth?mode=sign-in&redirectTo=%2Fdashboard%2Fnotifications");
  }

  const notifications = listNotificationsForUser(currentUser.id);
  const unreadNotifications = notifications.filter((notification) => !notification.readAt);
  const readNotifications = notifications.filter((notification) => Boolean(notification.readAt));
  const unreadCount = notifications.filter((notification) => !notification.readAt).length;
  const primaryHref = currentUser.role === "creator" ? "/creator/hires" : currentUser.role === "admin" ? "/admin/hires" : "/dashboard/hires";
  const primaryLabel = currentUser.role === "creator" ? "Open creator hires" : currentUser.role === "admin" ? "Open admin hires" : "Open brand hires";
  const resolvedSearchParams = searchParams ? await searchParams : undefined;
  const feedbackMessage = resolvedSearchParams?.status ? notificationStatusMessages[resolvedSearchParams.status] : undefined;

  return (
    <main className="app-shell">
      <div className="shell-container">
        <MarketplaceTopNav activeHref="/dashboard/notifications" />

        <GlassPanel className="hero-card">
          <div className="hero-card__header">
            <div>
              <p className="foundation-eyebrow">Notifications</p>
              <h1 className="hero-card__title">Track hire, message, payout, and moderation events from one feed.</h1>
            </div>
            <div className="sort-badge">Unread: {unreadCount}</div>
          </div>
          <p className="hero-card__copy">
            Notifications are now generated by the same server-owned commands that create hires, messages, review states, payouts, and admin actions, so the feed reflects real operational state instead of placeholder activity.
          </p>
          {feedbackMessage ? <span className="badge badge--accent">{feedbackMessage}</span> : null}
          <div className="auth-actions">
            <Link className="chip" href={primaryHref}>
              {primaryLabel}
            </Link>
            {notifications.length > 0 ? (
              <form action="/dashboard/notifications/read" method="post">
                <button className="chip chip--solid" type="submit">
                  Mark all read
                </button>
              </form>
            ) : null}
          </div>
        </GlassPanel>

        <section className="profile-score-grid" aria-label="Notification summary">
          <GlassPanel className="profile-score-card">
            <span className="metric-pill__label">Unread</span>
            <strong className="profile-score-card__value profile-score-card__value--small">{unreadNotifications.length}</strong>
            <p className="profile-score-card__copy">Unread events stay at the top of the feed until a user explicitly clears them.</p>
          </GlassPanel>
          <GlassPanel className="profile-score-card">
            <span className="metric-pill__label">Read</span>
            <strong className="profile-score-card__value profile-score-card__value--small">{readNotifications.length}</strong>
            <p className="profile-score-card__copy">Handled events remain visible for context without competing with new work.</p>
          </GlassPanel>
          <GlassPanel className="profile-score-card">
            <span className="metric-pill__label">Total events</span>
            <strong className="profile-score-card__value profile-score-card__value--small">{notifications.length}</strong>
            <p className="profile-score-card__copy">Hire, message, payout, and moderation activity all land in the same event feed.</p>
          </GlassPanel>
        </section>

        <section className="profile-sections">
          <GlassPanel className="profile-section-card">
            <div className="profile-section-card__header">
              <div>
                <h2 className="results-toolbar__title">Unread first</h2>
                <p className="results-toolbar__subtitle">The newest work stays grouped together so the feed reads like an inbox instead of a flat log.</p>
              </div>
            </div>
            <div className="profile-list-grid">
              {unreadNotifications.length > 0 ? unreadNotifications.map((notification) => (
                <div key={notification.id} className="profile-list-card">
                  <h3 className="panel-card-title">{notification.title}</h3>
                  <p className="profile-list-card__copy">{notification.body}</p>
                  <p className="profile-list-card__copy">Unread</p>
                  <div className="auth-actions">
                    <Link className="chip chip--solid" href={notification.link}>
                      Open event
                    </Link>
                    <form action="/dashboard/notifications/read" method="post">
                      <input name="notificationId" type="hidden" value={notification.id} />
                      <button className="chip" type="submit">
                        Mark read
                      </button>
                    </form>
                  </div>
                </div>
              )) : (
                <div className="profile-list-card">
                  <h3 className="panel-card-title">No unread notifications</h3>
                  <p className="profile-list-card__copy">New hire, message, payout, and moderation events will surface here first.</p>
                </div>
              )}
            </div>
          </GlassPanel>

          <GlassPanel className="profile-section-card">
            <div className="profile-section-card__header">
              <div>
                <h2 className="results-toolbar__title">Handled events</h2>
                <p className="results-toolbar__subtitle">Read items stay in the feed as a lightweight audit trail after the immediate work is cleared.</p>
              </div>
            </div>
            <div className="profile-list-grid">
              {readNotifications.length > 0 ? readNotifications.map((notification) => (
                <div key={notification.id} className="profile-list-card">
                  <h3 className="panel-card-title">{notification.title}</h3>
                  <p className="profile-list-card__copy">{notification.body}</p>
                  <p className="profile-list-card__copy">Read</p>
                  <div className="auth-actions">
                    <Link className="chip" href={notification.link}>
                      Open event
                    </Link>
                  </div>
                </div>
              )) : (
                <div className="profile-list-card">
                  <h3 className="panel-card-title">No handled events yet</h3>
                  <p className="profile-list-card__copy">Read notifications will move here automatically so the top section stays focused.</p>
                </div>
              )}
            </div>
          </GlassPanel>
        </section>
      </div>
    </main>
  );
}